root_dir: # 【需更動】ERA5 nc 月檔資料夾路徑
output_dir: # 【需更動】轉換後  ERA nc 小時檔放置資料夾路徑
time_variable: "valid_time" # ERA5 nc 檔裡時間變數的名稱
workers: 20 # 平行處理的核心數，可依據CPU核心數調整
dt_hours: 1 # 資料時間間隔，單位為小時
variables: # ERA5檔名的變數名稱 
  - "mslp"
  - "sp"
  - "tcwv"
  - "t2m"
  - "u10"
  - "v10"
  - "q1000"
  - "q850"
  - "q500"
  - "q250"
  - "t1000"
  - "t850"
  - "t500"
  - "t250"
  - "u1000"
  - "u850"
  - "u500"
  - "u250"
  - "v1000"
  - "v850"
  - "v500"
  - "v250"
  - "z1000"
  - "z850"
  - "z500"
  - "z250"

# ERA5 檔名：NC檔內變數名稱對照表
variable_mapping:
  mslp: "msl"  # 檔名：mslp NC檔內的變數：msl
  sp: "sp"
  tcwv: "tcwv"
  t2m: "t2m"
  u10: "u10"
  v10: "v10"
  q1000: "q"
  q850: "q"
  q500: "q"
  q250: "q"
  t1000: "t"
  t850: "t"
  t500: "t"
  t250: "t"
  u1000: "u"
  u850: "u"
  u500: "u"
  u250: "u"
  v1000: "v"
  v850: "v"
  v500: "v"
  v250: "v"
  z1000: "z"
  z850: "z"
  z500: "z"
  z250: "z"