#!/usr/bin/env python3
"""
Inspect Zarr stores generated by to_zarr.py for StormCast inference.

This tool provides detailed information about:
- LowRes and HighRes zarr stores
- Invariants zarr store
- Normalization statistics
- Data shapes, channels, coordinates, and value ranges

Usage:
    python inspect_zarr.py /path/to/zarr_output
    python inspect_zarr.py /path/to/specific.zarr
"""

import argparse
import pathlib
import sys
from typing import Optional

import numpy as np

try:
    import xarray as xr
    HAS_XARRAY = True
except ImportError:
    HAS_XARRAY = False
    xr = None

try:
    import zarr
    HAS_ZARR = True
except ImportError:
    HAS_ZARR = False
    zarr = None


def print_separator(char: str = "=", length: int = 70) -> None:
    print(char * length)


def print_header(title: str) -> None:
    print_separator()
    print(f"  {title}")
    print_separator()


def inspect_zarr_store(zarr_path: pathlib.Path) -> None:
    """Inspect a single Zarr store and print detailed information."""
    if not HAS_XARRAY:
        print("ERROR: xarray is required to inspect Zarr stores")
        return
    
    if not zarr_path.exists():
        print(f"ERROR: Path does not exist: {zarr_path}")
        return
    
    print_header(f"Zarr Store: {zarr_path.name}")
    print(f"  Full Path: {zarr_path}")
    
    try:
        ds = xr.open_zarr(zarr_path, consolidated=True)
    except Exception as e:
        print(f"  ERROR opening zarr: {e}")
        return
    
    # Print dimensions
    print(f"\n  Dimensions:")
    for dim, size in ds.dims.items():
        print(f"    {dim}: {size}")
    
    # Print coordinates
    print(f"\n  Coordinates:")
    for coord_name, coord in ds.coords.items():
        coord_vals = coord.values
        if coord_name == "time":
            print(f"    {coord_name}: {coord_vals}")
        elif coord_name == "channel":
            channels = list(coord_vals)
            print(f"    {coord_name}: {len(channels)} channels")
            print(f"      {channels}")
        elif coord_name in ["latitude", "longitude"]:
            if coord_vals.ndim == 2:
                print(f"    {coord_name}: shape={coord_vals.shape}, "
                      f"range=[{coord_vals.min():.4f}, {coord_vals.max():.4f}]")
            else:
                print(f"    {coord_name}: {coord_vals.shape}")
        else:
            if hasattr(coord_vals, '__len__') and len(coord_vals) <= 10:
                print(f"    {coord_name}: {coord_vals}")
            else:
                print(f"    {coord_name}: shape={coord_vals.shape if hasattr(coord_vals, 'shape') else 'scalar'}")
    
    # Print data variables
    print(f"\n  Data Variables:")
    for var_name, var in ds.data_vars.items():
        print(f"    {var_name}:")
        print(f"      dims: {var.dims}")
        print(f"      shape: {var.shape}")
        print(f"      dtype: {var.dtype}")
        
        # Compute statistics for numeric arrays
        if np.issubdtype(var.dtype, np.number):
            vals = var.values
            finite_vals = vals[np.isfinite(vals)]
            if finite_vals.size > 0:
                print(f"      min: {finite_vals.min():.6g}")
                print(f"      max: {finite_vals.max():.6g}")
                print(f"      mean: {finite_vals.mean():.6g}")
                print(f"      std: {finite_vals.std():.6g}")
                nan_count = np.isnan(vals).sum()
                if nan_count > 0:
                    print(f"      NaN count: {nan_count} ({100*nan_count/vals.size:.2f}%)")
    
    # Print per-channel statistics if applicable
    for var_name in ds.data_vars:
        if "channel" in ds[var_name].dims and "time" in ds[var_name].dims:
            print(f"\n  Per-Channel Statistics for '{var_name}':")
            channels = ds.coords["channel"].values
            data = ds[var_name].values  # (time, channel, y, x)
            
            for i, ch in enumerate(channels):
                ch_data = data[:, i, :, :]
                finite = ch_data[np.isfinite(ch_data)]
                if finite.size > 0:
                    print(f"    {ch:12s}: min={finite.min():12.4g}, max={finite.max():12.4g}, "
                          f"mean={finite.mean():12.4g}, std={finite.std():12.4g}")
    
    ds.close()


def inspect_stats(stats_dir: pathlib.Path) -> None:
    """Inspect normalization statistics."""
    if not stats_dir.exists():
        return
    
    print_header(f"Statistics: {stats_dir}")
    
    means_path = stats_dir / "means.npy"
    stds_path = stats_dir / "stds.npy"
    channels_path = stats_dir / "channels.txt"
    
    channels = []
    if channels_path.exists():
        with open(channels_path, "r") as f:
            channels = [line.strip() for line in f if line.strip()]
        print(f"  Channels ({len(channels)}): {channels}")
    
    if means_path.exists():
        means = np.load(means_path)
        print(f"\n  Means: shape={means.shape}")
        if channels and len(channels) == len(means):
            for ch, m in zip(channels, means):
                print(f"    {ch:12s}: {m:12.6g}")
        else:
            print(f"    {means}")
    
    if stds_path.exists():
        stds = np.load(stds_path)
        print(f"\n  Stds: shape={stds.shape}")
        if channels and len(channels) == len(stds):
            for ch, s in zip(channels, stds):
                print(f"    {ch:12s}: {s:12.6g}")
        else:
            print(f"    {stds}")


def inspect_invariants(invariants_dir: pathlib.Path) -> None:
    """Inspect invariants zarr store."""
    zarr_path = invariants_dir / "invariants.zarr"
    if zarr_path.exists():
        inspect_zarr_store(zarr_path)


def inspect_output_directory(output_dir: pathlib.Path) -> None:
    """Inspect a complete output directory from to_zarr.py."""
    print_header(f"Inspecting Output Directory: {output_dir}")
    
    # List contents
    print("\n  Directory Contents:")
    for item in sorted(output_dir.iterdir()):
        if item.is_dir():
            print(f"    [DIR]  {item.name}/")
        else:
            print(f"    [FILE] {item.name}")
    
    # Check for LowRes
    lowres_dir = output_dir / "LowRes"
    if lowres_dir.exists():
        print("\n")
        for zarr_path in sorted(lowres_dir.glob("*.zarr")):
            inspect_zarr_store(zarr_path)
        
        stats_dir = lowres_dir / "stats"
        if stats_dir.exists():
            print("\n")
            inspect_stats(stats_dir)
    
    # Check for HighRes
    highres_dir = output_dir / "HighRes"
    if highres_dir.exists():
        print("\n")
        for zarr_path in sorted(highres_dir.glob("*.zarr")):
            inspect_zarr_store(zarr_path)
        
        stats_dir = highres_dir / "stats"
        if stats_dir.exists():
            print("\n")
            inspect_stats(stats_dir)
    
    # Check for invariants
    invariants_dir = output_dir / "invariants"
    if invariants_dir.exists():
        print("\n")
        inspect_invariants(invariants_dir)


def main():
    parser = argparse.ArgumentParser(
        description="Inspect Zarr stores generated by to_zarr.py"
    )
    parser.add_argument(
        "path",
        type=str,
        help="Path to zarr store or output directory",
    )
    parser.add_argument(
        "--channels-only",
        action="store_true",
        help="Only print channel names",
    )
    
    args = parser.parse_args()
    path = pathlib.Path(args.path)
    
    if not path.exists():
        print(f"ERROR: Path does not exist: {path}")
        sys.exit(1)
    
    # Determine what kind of path this is
    if path.suffix == ".zarr" or (path / ".zattrs").exists():
        # Single zarr store
        inspect_zarr_store(path)
    elif (path / "LowRes").exists() or (path / "HighRes").exists() or (path / "invariants").exists():
        # Output directory from to_zarr.py
        inspect_output_directory(path)
    elif path.is_dir():
        # Check if it contains zarr stores
        zarr_stores = list(path.glob("**/*.zarr"))
        if zarr_stores:
            for zarr_path in sorted(zarr_stores):
                inspect_zarr_store(zarr_path)
                print("\n")
        else:
            print(f"No zarr stores found in: {path}")
    else:
        print(f"Unknown path type: {path}")
        sys.exit(1)
    
    print_separator()
    print("Inspection complete.")


if __name__ == "__main__":
    main()
