#!/usr/bin/env python3
"""
Plot all variables from Zarr stores generated by to_zarr.py.

This tool creates visualizations for:
- LowRes variables (24 channels from GRIB)
- HighRes variables (4 channels from RWRF + QPEPRE)
- Invariants (lsm, orog)

Usage:
    python plot_zarr.py /path/to/zarr/output --output /path/to/plots
    python plot_zarr.py /path/to/zarr/output  # saves to ./plots by default
"""

from __future__ import annotations

import argparse
import pathlib
from typing import Dict, List, Optional, Tuple

import numpy as np

try:
    import xarray as xr
    HAS_XARRAY = True
except ImportError:
    HAS_XARRAY = False
    xr = None

try:
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False
    plt = None

try:
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature
    HAS_CARTOPY = True
except ImportError:
    HAS_CARTOPY = False
    ccrs = None


# ---------------------------------------------------------------------------
# Variable metadata for better plotting
# ---------------------------------------------------------------------------

VARIABLE_INFO = {
    # Surface variables
    "mslp": {"name": "Mean Sea Level Pressure", "unit": "Pa", "cmap": "viridis"},
    "t2m": {"name": "2m Temperature", "unit": "K", "cmap": "RdYlBu_r"},
    "u10": {"name": "10m U-Wind", "unit": "m/s", "cmap": "RdBu_r"},
    "v10": {"name": "10m V-Wind", "unit": "m/s", "cmap": "RdBu_r"},
    "qpepre": {"name": "QPE Precipitation", "unit": "mm", "cmap": "Blues"},
    
    # Specific humidity at pressure levels
    "q1000": {"name": "Specific Humidity @ 1000hPa", "unit": "kg/kg", "cmap": "YlGnBu"},
    "q850": {"name": "Specific Humidity @ 850hPa", "unit": "kg/kg", "cmap": "YlGnBu"},
    "q500": {"name": "Specific Humidity @ 500hPa", "unit": "kg/kg", "cmap": "YlGnBu"},
    "q250": {"name": "Specific Humidity @ 250hPa", "unit": "kg/kg", "cmap": "YlGnBu"},
    
    # Temperature at pressure levels
    "t1000": {"name": "Temperature @ 1000hPa", "unit": "K", "cmap": "RdYlBu_r"},
    "t850": {"name": "Temperature @ 850hPa", "unit": "K", "cmap": "RdYlBu_r"},
    "t500": {"name": "Temperature @ 500hPa", "unit": "K", "cmap": "RdYlBu_r"},
    "t250": {"name": "Temperature @ 250hPa", "unit": "K", "cmap": "RdYlBu_r"},
    
    # U-wind at pressure levels
    "u1000": {"name": "U-Wind @ 1000hPa", "unit": "m/s", "cmap": "RdBu_r"},
    "u850": {"name": "U-Wind @ 850hPa", "unit": "m/s", "cmap": "RdBu_r"},
    "u500": {"name": "U-Wind @ 500hPa", "unit": "m/s", "cmap": "RdBu_r"},
    "u250": {"name": "U-Wind @ 250hPa", "unit": "m/s", "cmap": "RdBu_r"},
    
    # V-wind at pressure levels
    "v1000": {"name": "V-Wind @ 1000hPa", "unit": "m/s", "cmap": "RdBu_r"},
    "v850": {"name": "V-Wind @ 850hPa", "unit": "m/s", "cmap": "RdBu_r"},
    "v500": {"name": "V-Wind @ 500hPa", "unit": "m/s", "cmap": "RdBu_r"},
    "v250": {"name": "V-Wind @ 250hPa", "unit": "m/s", "cmap": "RdBu_r"},
    
    # Geopotential at pressure levels
    "z1000": {"name": "Geopotential @ 1000hPa", "unit": "m²/s²", "cmap": "terrain"},
    "z850": {"name": "Geopotential @ 850hPa", "unit": "m²/s²", "cmap": "terrain"},
    "z500": {"name": "Geopotential @ 500hPa", "unit": "m²/s²", "cmap": "terrain"},
    "z250": {"name": "Geopotential @ 250hPa", "unit": "m²/s²", "cmap": "terrain"},
    
    # Invariants
    "lsm": {"name": "Land-Sea Mask", "unit": "", "cmap": "RdYlGn"},
    "orog": {"name": "Orography", "unit": "m", "cmap": "terrain"},
}


def get_variable_info(var_name: str) -> Dict:
    """Get plotting info for a variable."""
    return VARIABLE_INFO.get(var_name, {
        "name": var_name,
        "unit": "",
        "cmap": "viridis"
    })


# ---------------------------------------------------------------------------
# Plotting functions
# ---------------------------------------------------------------------------

def plot_single_variable(
    data: np.ndarray,
    lon: np.ndarray,
    lat: np.ndarray,
    var_name: str,
    title: str,
    output_path: pathlib.Path,
    time_str: Optional[str] = None,
    use_cartopy: bool = True,
) -> None:
    """Plot a single variable and save to file."""
    info = get_variable_info(var_name)
    
    fig_width = 10
    fig_height = 8
    
    if use_cartopy and HAS_CARTOPY:
        fig, ax = plt.subplots(
            figsize=(fig_width, fig_height),
            subplot_kw={"projection": ccrs.PlateCarree()}
        )
        
        # Plot data
        im = ax.pcolormesh(
            lon, lat, data,
            transform=ccrs.PlateCarree(),
            cmap=info["cmap"],
            shading="auto"
        )
        
        # Add map features
        ax.coastlines(resolution="10m", linewidth=0.5)
        ax.add_feature(cfeature.BORDERS, linewidth=0.3)
        ax.add_feature(cfeature.LAND, alpha=0.1)
        ax.add_feature(cfeature.OCEAN, alpha=0.1)
        
        # Add gridlines
        gl = ax.gridlines(draw_labels=True, linewidth=0.3, alpha=0.5)
        gl.top_labels = False
        gl.right_labels = False
        
    else:
        fig, ax = plt.subplots(figsize=(fig_width, fig_height))
        
        im = ax.pcolormesh(lon, lat, data, cmap=info["cmap"], shading="auto")
        ax.set_xlabel("Longitude")
        ax.set_ylabel("Latitude")
    
    # Add colorbar
    cbar = plt.colorbar(im, ax=ax, shrink=0.8, pad=0.02)
    unit_str = f" ({info['unit']})" if info["unit"] else ""
    cbar.set_label(f"{info['name']}{unit_str}")
    
    # Set title
    full_title = f"{title}\n{info['name']}"
    if time_str:
        full_title += f"\n{time_str}"
    ax.set_title(full_title, fontsize=12)
    
    # Add statistics annotation
    stats_text = f"min: {np.nanmin(data):.4g}, max: {np.nanmax(data):.4g}, mean: {np.nanmean(data):.4g}"
    fig.text(0.5, 0.02, stats_text, ha="center", fontsize=9, style="italic")
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {output_path}")


def plot_zarr_store(
    store_path: pathlib.Path,
    output_dir: pathlib.Path,
    data_var: str,
    prefix: str,
    use_cartopy: bool = True,
) -> None:
    """Plot all channels from a Zarr store."""
    if not store_path.exists():
        print(f"Store not found: {store_path}")
        return
    
    print(f"\nPlotting {prefix} from: {store_path}")
    
    ds = xr.open_zarr(store_path)
    
    # Get coordinates
    if "latitude" in ds.coords:
        lat = ds.coords["latitude"].values
        lon = ds.coords["longitude"].values
    else:
        # Fallback to y/x indices
        lat = ds.coords["y"].values
        lon = ds.coords["x"].values
        lat, lon = np.meshgrid(lat, lon, indexing="ij")
    
    # Get time string if available
    time_str = None
    if "time" in ds.coords and ds.coords["time"].size > 0:
        time_val = ds.coords["time"].values[0]
        time_str = str(np.datetime_as_string(time_val, unit="s"))
    
    # Get channels
    if "channel" in ds.coords:
        channels = ds.coords["channel"].values
    else:
        channels = []
    
    # Get data variable
    if data_var not in ds.data_vars:
        print(f"  Data variable '{data_var}' not found")
        return
    
    data = ds[data_var].values
    
    # Handle dimensions: (time, channel, y, x) or (channel, y, x)
    if data.ndim == 4:
        data = data[0]  # Take first time step
    
    # Plot each channel
    for i, ch in enumerate(channels):
        ch_str = str(ch)
        ch_data = data[i]
        
        output_path = output_dir / f"{prefix}_{ch_str}.png"
        plot_single_variable(
            ch_data, lon, lat, ch_str,
            title=prefix,
            output_path=output_path,
            time_str=time_str,
            use_cartopy=use_cartopy,
        )
    
    ds.close()


def plot_invariants(
    store_path: pathlib.Path,
    output_dir: pathlib.Path,
    use_cartopy: bool = True,
) -> None:
    """Plot invariant fields."""
    if not store_path.exists():
        print(f"Store not found: {store_path}")
        return
    
    print(f"\nPlotting invariants from: {store_path}")
    
    ds = xr.open_zarr(store_path)
    
    # Get coordinates
    if "latitude" in ds.coords:
        lat = ds.coords["latitude"].values
        lon = ds.coords["longitude"].values
    else:
        lat = ds.coords["y"].values
        lon = ds.coords["x"].values
        lat, lon = np.meshgrid(lat, lon, indexing="ij")
    
    # Get channels
    if "channel" in ds.coords:
        channels = ds.coords["channel"].values
    else:
        channels = []
    
    # Find the invariants data variable
    data_var = None
    for var in ds.data_vars:
        if "invariant" in var.lower():
            data_var = var
            break
    
    if data_var is None:
        print("  No invariants data variable found")
        return
    
    data = ds[data_var].values
    
    # Plot each channel
    for i, ch in enumerate(channels):
        ch_str = str(ch)
        ch_data = data[i]
        
        output_path = output_dir / f"invariant_{ch_str}.png"
        plot_single_variable(
            ch_data, lon, lat, ch_str,
            title="Invariants",
            output_path=output_path,
            time_str=None,
            use_cartopy=use_cartopy,
        )
    
    ds.close()


def create_summary_plot(
    input_dir: pathlib.Path,
    output_dir: pathlib.Path,
    use_cartopy: bool = True,
) -> None:
    """Create a summary plot with key variables."""
    print("\nCreating summary plot...")
    
    # Key variables to include in summary
    key_vars = {
        "LowRes": ["mslp", "t2m", "u10", "v10", "z500", "t850"],
        "HighRes": ["t2m", "u10", "v10", "qpepre"],
    }
    
    # Collect data
    plot_data = []
    
    for res_type, var_list in key_vars.items():
        store_path = input_dir / res_type / "inference.zarr"
        if not store_path.exists():
            continue
        
        ds = xr.open_zarr(store_path)
        
        if "latitude" in ds.coords:
            lat = ds.coords["latitude"].values
            lon = ds.coords["longitude"].values
        else:
            lat = ds.coords["y"].values
            lon = ds.coords["x"].values
            lat, lon = np.meshgrid(lat, lon, indexing="ij")
        
        channels = list(ds.coords["channel"].values) if "channel" in ds.coords else []
        data = ds[res_type].values
        if data.ndim == 4:
            data = data[0]
        
        for var in var_list:
            if var in channels:
                idx = channels.index(var)
                plot_data.append({
                    "name": var,
                    "data": data[idx],
                    "lon": lon,
                    "lat": lat,
                    "type": res_type,
                })
        
        ds.close()
    
    if not plot_data:
        print("  No data found for summary plot")
        return
    
    # Create figure
    n_plots = len(plot_data)
    n_cols = min(4, n_plots)
    n_rows = (n_plots + n_cols - 1) // n_cols
    
    fig_width = 4 * n_cols
    fig_height = 3.5 * n_rows
    
    if use_cartopy and HAS_CARTOPY:
        fig, axes = plt.subplots(
            n_rows, n_cols,
            figsize=(fig_width, fig_height),
            subplot_kw={"projection": ccrs.PlateCarree()}
        )
    else:
        fig, axes = plt.subplots(n_rows, n_cols, figsize=(fig_width, fig_height))
    
    axes = np.atleast_2d(axes)
    
    for idx, pdata in enumerate(plot_data):
        row = idx // n_cols
        col = idx % n_cols
        ax = axes[row, col]
        
        info = get_variable_info(pdata["name"])
        
        if use_cartopy and HAS_CARTOPY:
            im = ax.pcolormesh(
                pdata["lon"], pdata["lat"], pdata["data"],
                transform=ccrs.PlateCarree(),
                cmap=info["cmap"],
                shading="auto"
            )
            ax.coastlines(resolution="10m", linewidth=0.3)
        else:
            im = ax.pcolormesh(
                pdata["lon"], pdata["lat"], pdata["data"],
                cmap=info["cmap"],
                shading="auto"
            )
        
        ax.set_title(f"{pdata['type']}: {info['name']}", fontsize=10)
        plt.colorbar(im, ax=ax, shrink=0.6)
    
    # Hide empty subplots
    for idx in range(n_plots, n_rows * n_cols):
        row = idx // n_cols
        col = idx % n_cols
        axes[row, col].set_visible(False)
    
    plt.suptitle("Variable Summary", fontsize=14, y=1.02)
    plt.tight_layout()
    
    output_path = output_dir / "summary.png"
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {output_path}")


# ---------------------------------------------------------------------------
# Main function
# ---------------------------------------------------------------------------

def plot_all_variables(
    input_dir: pathlib.Path,
    output_dir: pathlib.Path,
    use_cartopy: bool = True,
    create_summary: bool = True,
) -> None:
    """Plot all variables from to_zarr.py output."""
    if not HAS_XARRAY:
        raise RuntimeError("xarray is required for plotting")
    if not HAS_MATPLOTLIB:
        raise RuntimeError("matplotlib is required for plotting")
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Input directory: {input_dir}")
    print(f"Output directory: {output_dir}")
    print(f"Using Cartopy: {use_cartopy and HAS_CARTOPY}")
    
    # Plot LowRes
    lowres_store = input_dir / "LowRes" / "inference.zarr"
    lowres_output = output_dir / "LowRes"
    lowres_output.mkdir(parents=True, exist_ok=True)
    plot_zarr_store(lowres_store, lowres_output, "LowRes", "LowRes", use_cartopy)
    
    # Plot HighRes
    highres_store = input_dir / "HighRes" / "inference.zarr"
    highres_output = output_dir / "HighRes"
    highres_output.mkdir(parents=True, exist_ok=True)
    plot_zarr_store(highres_store, highres_output, "HighRes", "HighRes", use_cartopy)
    
    # Plot Invariants
    invariants_store = input_dir / "invariants" / "invariants.zarr"
    invariants_output = output_dir / "invariants"
    invariants_output.mkdir(parents=True, exist_ok=True)
    plot_invariants(invariants_store, invariants_output, use_cartopy)
    
    # Create summary plot
    if create_summary:
        create_summary_plot(input_dir, output_dir, use_cartopy)
    
    print(f"\nPlotting complete. Output saved to: {output_dir}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Plot all variables from Zarr stores generated by to_zarr.py"
    )
    parser.add_argument(
        "input_dir",
        type=str,
        help="Path to the output directory from to_zarr.py (contains LowRes/, HighRes/, invariants/)",
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="./plots",
        help="Output directory for plot images (default: ./plots)",
    )
    parser.add_argument(
        "--no-cartopy",
        action="store_true",
        help="Disable Cartopy for map projections (use simple plots)",
    )
    parser.add_argument(
        "--no-summary",
        action="store_true",
        help="Skip creating summary plot",
    )
    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()
    
    input_dir = pathlib.Path(args.input_dir)
    output_dir = pathlib.Path(args.output)
    
    if not input_dir.exists():
        print(f"Error: Input directory does not exist: {input_dir}")
        return 1
    
    use_cartopy = not args.no_cartopy
    create_summary = not args.no_summary
    
    plot_all_variables(input_dir, output_dir, use_cartopy, create_summary)
    return 0


if __name__ == "__main__":
    exit(main())
